
apiVersion: v1
kind: Pod
metadata:
  name: pod-to-worker3
spec:
  nodeName: easykube-worker3
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
  tolerations:
  - key: custom
    operator: Exists
    effect: NoSchedule
