apiVersion: v1
kind: ConfigMap
metadata:
  name: hitchecker-config 
  namespace: dev
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PAGE_TITLE: "Hello!"

---
apiVersion: v1
kind: Secret
metadata:
  name: hitchecker-secret
  namespace: dev
stringData:
  REDIS_PASSWORD: "password"


