apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-slow
provisioner: rancher.io/local-path
parameters:
  path: /opt/local-path/slow
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
