kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            authorization-mode: "AlwaysAllow"
            read-only-port: "10255"
            fail-swap-on: "false"
    extraPortMappings:
      - containerPort: 10255
        hostPort: 10255
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker