apiVersion: batch/v1
kind: Job
metadata:
  name: job-completions
spec:
  completions: 3
  parallelism: 1
  template:
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo '1회 실행'; sleep 5"]
      restartPolicy: Never

