apiVersion: batch/v1
kind: Job
metadata:
  name: job-timeout
spec:
  activeDeadlineSeconds: 10
  ttlSecondsAfterFinished: 40
  template:
    spec:
      containers:
      - name: timeout
        image: busybox
        command: ["sh", "-c", "echo '20초 후 완료'; sleep 20"]
      restartPolicy: Never
