
apiVersion: v1
kind: Pod
metadata:
  name: no-security-context-pod
spec:
  hostPID: true
  containers:
    - name: demo
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          pid1=$(cat /proc/1/comm)
          uid=$(id -u);
          if [ "$pid1" != "sh" ]; then
            echo "DANGER | host PID namespace exposed | pid1=$pid1 | uid=$uid"
          else
            echo "SAFE | isolated PID namespace | pid1=$pid1 | uid=$uid"
          fi
          sleep 3600
