apiVersion: v1
kind: Pod
metadata:
  name: logger-nginx
spec:
  containers:
  - name: main-app
    image: nginx:alpine-slim
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
  - name: sidecar
    image: busybox
    command: ["sh", "-c"]
    args: ["tail -f /logs/access.log"]
    volumeMounts:
    - name: logs
      mountPath: /logs
  volumes:
  - name: logs
    emptyDir: {}
