apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-backend-html
  namespace: dev
data:
  index.html: |
    <html>
    <body>
    <h1>HR Backend Service</h1>
    <p>This is HR backend pod responding.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr
  namespace: dev
  labels:
    app: hr
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
      tier: backend
  template:
    metadata:
      labels:
        app: hr
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: hr-backend-html
---
apiVersion: v1
kind: Service
metadata:
  name: hr-svc
  namespace: dev
spec:
  selector:
    app: hr-app   
    tier: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
