apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir
spec:
  containers:
    - name: main
      image: busybox
      command: ["sh", "-c", "sleep 60"]
      volumeMounts:
        - name: emptydir-data
          mountPath: /data
  volumes:
    - name: emptydir-data
      emptyDir: {}
