apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-network-checker
  labels:
    app: network-checker
spec:
  selector:
    matchLabels:
      app: network-checker
  template:
    metadata:
      labels:
        app: network-checker
    spec:
      containers:
      - name: netcheck
        image: busybox:1.35
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "node: $NODE_NAME | pod: $(hostname) | ping: $(ping -c1 -W1 8.8.8.8 >/dev/null && echo OK || echo FAIL) | dns: $(nslookup google.com >/dev/null 2>&1 && echo OK || echo FAIL)"
            sleep 20
          done
      restartPolicy: Always

