apiVersion: v1
kind: Pod
metadata:
  name: config-checker-autoupdate
spec:
  containers:
  - name: logger
    image: curlimages/curl:8.15.0
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "[sidecar] $(date) config 확인:"
        curl -s http://localhost:8000/check || echo "[sidecar] 실패"
        echo "---"
        sleep 5
      done
  - name: app
    image: devwikirepo/easykube-fastapi-config:1.0.1
    imagePullPolicy: Always 
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: app-config
      defaultMode: 0644
