apiVersion: batch/v1
kind: Job
metadata:
  name: job-timeout
spec:
  activeDeadlineSeconds: 10
  ttlSecondsAfterFinished: 40
  template:
    spec:
      containers:
      - name: timeout
        image: busybox:1.35
        command: ["sh", "-c", "echo '30초 후 완료'; sleep 30"]
      restartPolicy: Never
