apiVersion: v1
kind: Namespace
metadata:
  name: minio-demo

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-demo
spec:
  clusterIP: None  
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: minio-demo
spec:
  type: ClusterIP  
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio-demo
spec:
  serviceName: "minio"
  replicas: 3
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
          args:
            - server
            - --address=:9000
            - --console-address=:9001
            - http://minio-0.minio.minio-demo.svc.cluster.local/data
            - http://minio-1.minio.minio-demo.svc.cluster.local/data
            - http://minio-2.minio.minio-demo.svc.cluster.local/data
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin123
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio-demo
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-ui
                port:
                  number: 9001