apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: todos.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: todos
    singular: todo
    kind: Todo
    shortNames:
    - td
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              task:
                type: string
              done:
                type: boolean
