apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: nginx:alpine-slim
