apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-deploy
  name: db-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db-deploy
  template:
    metadata:
      labels:
        app: db-deploy
    spec:
      containers:
      - image: nginx:alpine-slim
        name: nginx
