apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
