apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay
  namespace: pay
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: pay-backend-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pay-backend-html
  namespace: pay
data:
  index.html: |
    <html>
    <body>
    <h1>PAY Backend Service</h1>
    <p>This is PAY backend pod responding.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: pay
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
