apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: nfs
  labels:
    app: nfs-server
spec:
  containers:
    - name: nfs-server
      image: itsthenetwork/nfs-server-alpine:latest
      securityContext:
        privileged: true
      env:
        - name: SHARED_DIRECTORY
          value: /exports
      ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
      volumeMounts:
        - name: nfs-volume
          mountPath: /exports
        - name: run
          mountPath: /run
        - name: varrun
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                echo "Creating directories in postStart..."
                for i in $(seq -w 1 10); do
                  mkdir -p /exports/$i
                done
                chmod -R 777 /exports
                echo "Done."
  volumes:
    - name: nfs-volume
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: varrun
      emptyDir: {}
    - name: tmp
      emptyDir: {}
