apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: nfs
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
