apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: Namespace
metadata:
  name: qa

---

apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
