apiVersion: v1
kind: Pod
metadata:
  name: qos-besteffort-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ["sh", "-c"]
    args: ["sleep 3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ["sh", "-c"]
    args: ["sleep 3600"]
    resources:
      requests:
        memory: "32Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ["sh", "-c"]
    args: ["sleep 3600"]
    resources:
      requests:
        cpu: "200m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "64Mi"
