apiVersion: v1
kind: Pod
metadata:
  name: hostpath-cat-checker
spec:
  nodeName: easykube-worker
  containers:
    - name: watcher
      image: busybox:1.35
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "📂 Contents of /data:"
            cat /mounted/test.txt || echo "⚠️ Cannot access /data"
            sleep 5
          done
      volumeMounts:
        - name: host-volume
          mountPath: /mounted
  volumes:
    - name: host-volume
      hostPath:
        path: /tmp/hostpath
        type: DirectoryOrCreate
